version: '3.8' 

services: 

  back: 
    image: back 
    ports: 
      - 8080:8080
    environment:
      - REDIS_HOST=redis-container
      - REQUEST_ORIGIN=http://localhost:5000
  front:
    image: front
    ports:
      - 5000:5000
  redis:
    image: redis:alpine
    container_name: redis-container